# Config file for automatic testing at travis-ci.org
language: python
python:
  - 3.4
  - 3.5
  - 3.6
env:
  - DJANGO_VERSION=\>=1.11,\<2.0
  - DJANGO_VERSION=\>=2.0,\<2.1
matrix:
  include:
    - python: 2.7
      env: DJANGO_VERSION=\>=1.11,\<2.0
install:
  - pip install --upgrade pip
  - pip install Django$DJANGO_VERSION --upgrade
  - pip install -q -e .
  - pip install -q -r requirements.txt
script:
  - coverage run --source djrichtextfield --branch manage.py test
after_success:
  - coveralls
branches:
  only:
    - master
sudo: false
