# Config file for automatic testing at travis-ci.org
language: python
python:
  - 3.6
  - 3.7
  - 3.8
env:
  - DJANGO_VERSION='Django>=2.2,<3.0'
  - DJANGO_VERSION='Django>=3.0,<3.1'
  - DJANGO_VERSION='Django>=3.1,<3.2'
install:
  - pip install --upgrade pip
  - pip install --upgrade $DJANGO_VERSION
  - pip install -q -e .
  - pip install -q -r requirements.txt
script:
  - coverage run --source djrichtextfield --branch manage.py test
after_success:
  - coveralls
branches:
  only:
    - master
